### ISSUE TITLE
(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials gj6sm7456452pjb.10 - gsmtp')

### ISSUE THREAD

**Issue by msMohit20** [CoreyMSchafer/code_snippets#135]
i am middle of the project and i was connecting django with gmail and i got this type of error.....

settings.py code for :

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

what should is in this !!!?

AND AS I AM PUTTING ANOTHER GMAIL ID IT SHOW THAT MAIL IS SENT BUT I CAN'T SEE THAT MAIL ANYWHERE???????????????????

**Comment by edward795** [comment]
Enable less secure app login for your google account, by default google doesn't allow you to login to smtp server.
Go here >>https://myaccount.google.com/lesssecureapps
and enable it and you will be good to go.

**Comment by msMohit20** [comment]
Thanks man

**Comment by dungranisahil7699** [comment]
Show This Error:
(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials m1sm1619710pjo.10 - gsmtp')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = '(Here I Give My Email)'
EMAIL_HOST_PASSWORD = '(Here I Give My Email Password)'

every thing is complete but email not send....!!!

**Comment by dungranisahil7699** [comment]
@edward795 
I alredy enable less secure app.
suggest me plz...

**Comment by dipakbera** [comment]
@edward795  
I have the same problem even after enabling a less secure app.

**Comment by tyhho** [comment]
@dipakbera 
Hello, would you mind sharing what solved your issue in the end? In our case we also enabled less secure app but the same error shows up. Thanks!

**Comment by dipakbera** [comment]
Can you show your error? Sent from Mail for Windows 10 From: Trevor Y. H. HoSent: 08 June 2021 18:10To: CoreyMSchafer/code_snippetsCc: dipakbera; MentionSubject: Re: [CoreyMSchafer/code_snippets] (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8 https://support.google.com/mail/?p=BadCredentials gj6sm7456452pjb.10 - gsmtp') ***@***.***Hello, would you mind sharing what solved your issue in the end? In our case we also enabled less secure app but the same error shows up. Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tyhho** [comment]
Thanks for getting back to me @dipakbera .
We solved the problem eventually by using a Google generated App Password. It looks like using the login pw was the problem for us before.
https://support.google.com/accounts/answer/185833?hl=en
2FA is still needed to generate this App pw but miraculously it solved the problem.
Thank you again!

**Comment by dipakbera** [comment]
From which platform, you are connecting me.Is it github or any else?welcome
you by the way.

**Comment by morteza2007h-dev** [comment]
enabled -->> https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4PW2mLzZHEaBJdC-4BjetXh3_23e0ttNOgSZxeff6S-MSTASUy81S5y7wRBe3BkCCj0hR0CKSmKHR9YCmFbDdpiaEkiOQ

**Comment by edchelstephens** [comment]
Hello guys,

Here's how we are able to solve this problem:

## Django SMPT Error answer:

https://support.google.com/mail/answer/7126229?p=BadCredentials&visit_id=637758197720369506-3330444657&rd=2#cantsignin&zippy=%2Ci-cant-sign-in-to-my-email-client

## Steps:

### 1. Create 2-Step Authentication
https://support.google.com/accounts/answer/185839


### 2. Create App Password
https://support.google.com/accounts/answer/185833

### 3. Use the APP password as your EMAIL_HOST_PASSWORD in your settings file

## It should work after that :+1:

**Comment by Rony390-hue** [comment]
how to show this using the alert box in GUI tkinter?

**Comment by Trickster811** [comment]
> how to show this using the alert box in GUI tkinter?
Hello!! What wnat you to show using alert box

**Comment by Trickster811** [comment]
> Hello guys,
> 
> Here's how we are able to solve this problem:
> ## Django SMPT Error answer:
> 
> https://support.google.com/mail/answer/7126229?p=BadCredentials&visit_id=637758197720369506-3330444657&rd=2#cantsignin&zippy=%2Ci-cant-sign-in-to-my-email-client
> ## Steps:
> ### 1. Create 2-Step Authentication
> 
> https://support.google.com/accounts/answer/185839
> ### 2. Create App Password
> 
> https://support.google.com/accounts/answer/185833
> ### 3. Use the APP password as your EMAIL_HOST_PASSWORD in your settings file
> ## It should work after that +1

Not working for me dear

**Comment by pratikgho** [comment]
enable access to the less secure app is ON, still seeing the same error? does anyone got solution.

**Comment by kaudit** [comment]
**From google.**

> _To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password_.


[https://support.google.com/accounts/answer/6010255?hl=en](url)

**Comment by Trickster811** [comment]
After turning Less Secure App to ON, generate an app password and you put
it your django project setting
EMAIL_HOST_USER = "your email"
DEFAULT_FROM_EMAIL = 'your default email'
SERVER_EMAIL = 'your server email
EMAIL_HOST_PASSWORD = "your generated app password"

**Comment by Trickster811** [comment]
What's the problem here??

**Comment by kaudit** [comment]
I tried to find that section of enabling less secure apps on google account, but it was available, This is the message I am getting from less secure app of my newly created account

> This setting is no longer available
 
From Google, the say they  longer supports the use of third-party apps or devices which ask you to sign in to
 your Google Account using only your username and password

**Comment by WeslleyxD** [comment]
FAZ ESSE TUTORIAL 
https://www.youtube.com/watch?v=uVDq4VOBMNM

**Comment by Trickster811** [comment]
Working Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [CoreyMSchafer/code_snippets] (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials gj6sm7456452pjb.10 - gsmtp') (#135)From: Weslley Pablo To: CoreyMSchafer/code_snippets CC: Joachim nedaouka ,Comment 
FAZ ESSE TUTORIAL
https://www.youtube.com/watch?v=uVDq4VOBMNM

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1151638907",
"url": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1151638907",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Osigbemes** [comment]
Hi, it seems google have disabled the toggle. 
I am unable to turn off less secure apps from my end

**Comment by Trickster811** [comment]
Hello!! Let me check itSent from my Huawei Mobile-------- Original Message --------Subject: Re: [CoreyMSchafer/code_snippets] (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials gj6sm7456452pjb.10 - gsmtp') (#135)From: osinaike gbemileke To: CoreyMSchafer/code_snippets CC: Joachim nedaouka ,Comment 
Hi, it seems google have disabled the toggle.
I am unable to turn off less secure apps from my end

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1152962375",
"url": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1152962375",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by OfficialMabz** [comment]
has anyone managed to come up with solution regarding this isssue.

**Comment by Trickster811** [comment]
Hello Guy !! Try to create a new email address just for test and check if LESS SECURE settings are still disabled. Let me know if done. Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [CoreyMSchafer/code_snippets] (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials gj6sm7456452pjb.10 - gsmtp') (#135)From: osinaike gbemileke To: CoreyMSchafer/code_snippets CC: Joachim nedaouka ,Comment 
Hi, it seems google have disabled the toggle.
I am unable to turn off less secure apps from my end

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1152962375",
"url": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1152962375",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by NadiaAzri** [comment]
> has anyone managed to come up with solution regarding this isssue.
waiting for the solution...

**Comment by OfficialMabz** [comment]
> > has anyone managed to come up with solution regarding this isssue.
> > waiting for the solution...

I have manged to fix my issue as Google have disabled the less secure apps recently. All I had to do was make my google account 2 factor authentication, then generate a new app password to use within the settings.py of django app for email password. Hope it helps

**Comment by xmsdos** [comment]
Test enabling “Access for less secure apps” (which just means the
client/app doesn’t use OAuth 2.0 - https://oauth.net/2/) for the account
you are trying to access.  It's found in the account settings on the
Security tab, Account permissions (not available to accounts with 2-step
verification enabled):
https://support.google.com/accounts/answer/6010255?hl=en

disable 2-step verification if enabled.

**Comment by xmsdos** [comment]
https://support.google.com/accounts/answer/6010255?hl=en

**Comment by Andreea523** [comment]
> > > has anyone managed to come up with solution regarding this isssue.
> > > waiting for the solution...
> 
> I have manged to fix my issue as Google have disabled the less secure apps recently. All I had to do was make my google account 2 factor authentication, then generate a new app password to use within the settings.py of django app for email password. Hope it helps

How did you generate a new password? 

I am trying to solve this problem, I have now the authentication in 2 factors, but I got block. And I need to solve faster this problem for a project that I need to present in few days

**Comment by xmsdos** [comment]
Follow this article: Create & use App Passwords
<https://support.google.com/accounts/answer/185833?hl=en>

**Comment by xmsdos** [comment]
Or this one:
https://devanswers.co/create-application-specific-password-gmail/

**Comment by shehantha08** [comment]
Go to your google account settings. Go to Security. then Turn on 2-step verification. Then App Password ta will be enable. From App Password you can generate password. use this password for authentication purposes

**Comment by hoainv1704** [comment]
I got a message on Security section that  [To protect your account, apps and devices that use less secure sign-in technology are blocked. To keep your account secure, Google will automatically turn this setting OFF if it’s not being used.](https://myaccount.google.com/lesssecureapps)]

**Comment by JJ1006** [comment]
> Show This Error: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8 https://support.google.com/mail/?p=BadCredentials m1sm1619710pjo.10 - gsmtp')
> 
> EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' EMAIL_HOST = 'smtp.gmail.com' EMAIL_USE_TLS = True EMAIL_PORT = 587 EMAIL_HOST_USER = '(Here I Give My Email)' EMAIL_HOST_PASSWORD = '(Here I Give My Email Password)'
> 
> every thing is complete but email not send....!!!

Now you cannot turn on less secure app as the deadline was 30th May 2022

**Comment by rahultalukdargithub** [comment]
I am using flask and same issue is happening for me . what to do

**Comment by T40FPV** [comment]
Hey, community, I did as follows and read everyone's comments in this thread and I keep getting the same kickback message.

**Comment by JJ1006** [comment]
Hey, I have fixed it. 
You need to go into your google accounts settings and then go to "security". Then scroll down to "app passwords". There you can generate a code that will work as a password. 

Do not share that code with anyone.

I was able to complete this. Hope this helps.

Feel free to ask more.

**Comment by JJ1006** [comment]
Hey, I have fixed it. 
You need to go into your google accounts settings and then go to "security". Then scroll down to "app passwords". There you can generate a code that will work as a password. 

Do not share that code with anyone.

I was able to complete this. I hope this helps.

Feel free to ask more.

**Comment by JJ1006** [comment]
> Hey, I have fixed it. You need to go into your google accounts settings and then go to "security". Then scroll down to "app passwords". There you can generate a code that will work as a password.
> 
> Do not share that code with anyone.
> 
> I was able to complete this. Hope this helps.
> 
> Feel free to ask more.

**Comment by T40FPV** [comment]
> > Hey, I have fixed it. You need to go into your google accounts settings and then go to "security". Then scroll down to "app passwords". There you can generate a code that will work as a password.
> > Do not share that code with anyone.
> > I was able to complete this. Hope this helps.
> > Feel free to ask more.

I did go into my Google Mail Settings and Turned on the 2 Step Verification and created the App Password. I put that password into my Settings.py and I still get:

**SMTPAuthenticationError at /register/
(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b22-20020a63e716000000b004298d7b6e70sm1862321pgi.54 - gsmtp')**

The Code Reads as follows:

Settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'from.********@gmail.com'
EMAIL_HOST_PASSWORD = '****************'



The code in 

Signals.py

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

from django.contrib.auth.models import User
from .models import Profile

from django.core.mail import send_mail
from django.conf import settings

# @receiver(post_save, sender=Profile)


def createProfile(sender, instance, created, **kwargs):
    if created:
        user = instance
        profile = Profile.objects.create(
            user=user,
            username=user.username,
            email=user.email,
            name=user.first_name,
        )

        subject = 'Welcome to DevSearch'
        message = 'We are glad you are here!'

        send_mail(
            subject,
            message, 
            settings.EMAIL_HOST_USER,
            [profile.email],
            fail_silently=False,
        )

**Comment by KathpaliaChirag** [comment]
> Enable less secure app login for your google account, by default google doesn't allow you to login to smtp server. Go here >>https://myaccount.google.com/lesssecureapps and enable it and you will be good to go.

it doesnt work anymore

**Comment by Trickster811** [comment]
YesI just turned ON my Google account LESS SECURE security settings and generate an app password. Then I was able to fix the problem Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [CoreyMSchafer/code_snippets] (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials gj6sm7456452pjb.10 - gsmtp') (#135)From: Mahbub Rahman To: CoreyMSchafer/code_snippets CC: Joachim nedaouka ,Comment 
has anyone managed to come up with solution regarding this isssue.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1153002782",
"url": "https://github.com/CoreyMSchafer/code_snippets/issues/135#issuecomment-1153002782",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
