### ISSUE TITLE
supervisor can't find gunicorn

### ISSUE THREAD

**Issue by juangf7** [CoreyMSchafer/code_snippets#82]
using this file:

https://github.com/CoreyMSchafer/code_snippets/blob/master/Python/Flask_Blog/snippets/supervisor.conf

`sudo supervisorctl status `

I'm getting this error:

`app                              FATAL     can't find command '/home/MY_USER/site/venv/bin/gunicorn'`

Please advise. Thanks a lot.

**Comment by animax1991** [comment]
How you resolve the problem? I'm facing to this :(

**Comment by juangf7** [comment]
> How you resolve the problem? I'm facing to this :(

Sorry, long time this happened, I don't remember how I fixed this :(

**Comment by animax1991** [comment]
It's ok. It took me nearly 2 days to find the solution but still can't fix :(
